[project]
name = "Particle_allocation_malaria"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "particles>=0.4,<0.5",
    "numpy>=1.26.4",
    "ipywidgets>=8.1.8",
]
